version: '2'
services:
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./redis_storage:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      'redis-server /usr/local/etc/redis/redis.conf'