fos_oauth_server:
  db_driver: mongodb       # Drivers available: orm, mongodb, or propel
  client_class:        App\ApiBundle\Document\Client
  access_token_class:  App\ApiBundle\Document\AccessToken
  refresh_token_class: App\ApiBundle\Document\RefreshToken
  auth_code_class:     App\ApiBundle\Document\AuthCode
  service:
    user_provider: fos_user.user_provider.username