version: '2'
services:
  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf/mongod.conf:/etc/mongod.conf
      - ./db_storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
      - "28017:28017"
      - "29017:29017"
