version: '2'
services:
  mongo:
    container_name: mongo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- ./db_storage:/var/lib/mongo  # Link to your local database, it will be imported when running.
      - ./conf/mongod.conf:/etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
      - "28017:28017"
      - "29017:29017"
