version: '2'
services:
  es:
    container_name: es
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    volumes:
      - ./conf/:/usr/share/elasticsearch/config/
      - ./es_storage:/usr/share/elasticsearch/data
