version: '2'
services:
  db:
    container_name: mysql
#    image: percona:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db_storage:/var/lib/mysql  # Link to your local database, it will be imported when running.
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"